pipeline {
    agent { node { label 'jenkins-kvmtest-workers' } }

    options {
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '30'))

    }

    triggers {
        pollSCM('@midnight')
    }


    stages {
        stage('Prepare') {
            steps {
                dir('sonic-mgmt') {
                    checkout([$class: 'GitSCM',
                              branches: [[name: '*/master']],
                              userRemoteConfigs: [[url: 'https://github.com/Azure/sonic-mgmt']]])
                }

                dir('sonic-buildimage') {
                    checkout([$class: 'GitSCM',
                          branches: [[name: 'refs/heads/master']],
                          extensions: [[$class: 'SubmoduleOption',
                                        disableSubmodules: false,
                                        parentCredentials: false,
                                        recursiveSubmodules: true,
                                        reference: '',
                                        trackingSubmodules: false]],
                          userRemoteConfigs: [[url: 'http://github.com/Azure/sonic-buildimage']]])
                }
            }
        }

        stage('Build') {
            steps {
                sh '''
#!/bin/bash -xe

cd sonic-buildimage

git submodule foreach --recursive '[ -f .git ] && echo "gitdir: $(realpath --relative-to=. $(cut -d" " -f2 .git))" > .git'

make configure PLATFORM=vs

sudo bash -c "echo 1 > /proc/sys/vm/compact_memory"

make SONIC_CONFIG_BUILD_JOBS=1 INSTALL_DEBUG_TOOLS=y target/sonic-vs.img.gz
mv target/sonic-vs.bin target/sonic-vs-dbg.bin
mv target/sonic-vs.img.gz target/sonic-vs-dbg.img.gz
mv target/sonic-vs.img.gz.log target/sonic-vs-dbg.img.gz.log
make SONIC_CONFIG_BUILD_JOBS=1 target/sonic-vs.img.gz

mv target ../
'''
            }
        }

        stage('Test') {
            steps {
                wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                    lock(resource: "kvmtest_${env.NODE_NAME}") {
                        withCredentials([sshUserPrivateKey(credentialsId: '2b6b6afe-4892-41d1-967c-d683e7773727', keyFileVariable: 'PRIVATE_KEY')]) {
                            sh './scripts/vs/buildimage-vs-image/test.sh'
				        }
                    }
                }
            }
        }
    }
    post {

        success {
            archiveArtifacts(artifacts: 'target/**')
        }
        fixed {
            slackSend(color:'#00FF00', message: "Build job back to normal: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        regression {
            slackSend(color:'#FF0000', message: "Build job Regression: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        cleanup {
            cleanWs(disableDeferredWipeout: false, deleteDirs: true, notFailBuild: true)
        }
    }
}
