pipeline {
    agent { node { label 'sonic-slave-buster' } }

    stages {
        stage('Prepare') {
            steps {
                dir('sonic-swss-common') {
                    checkout([$class: 'GitSCM',
                              branches: [[name: '${sha1}']],
                              userRemoteConfigs: [[url: 'http://github.com/Azure/sonic-swss-common',
                                                   refspec: '+refs/pull/*:refs/remotes/origin/pr/*']]])
                }
                copyArtifacts(projectName: 'vs/buildimage-vs-all', filter: '**/*.deb', target: 'buildimage', flatten: false)
            }
        }

        stage('Build') {
            steps {
                sh './scripts/common/sonic-swss-common-build/build.sh'
            }
        }

        stage('Test') {
            steps {
                sh './scripts/common/sonic-swss-common-build/test.sh'
            }
        }
    }
    post {

        success {
            archiveArtifacts(artifacts: 'target/*.deb')
        }
    }
}
