pipeline {
    agent { node { label 'sonic-slave-buster' } }

    stages {
        stage('Prepare') {
            steps {
                dir('sonic-mgmt-framework') {
                    checkout([$class: 'GitSCM',
                          branches: [[name: '${sha1}']],
                          userRemoteConfigs: [[url: 'http://github.com/Azure/sonic-mgmt-framework',
                                               refspec: '+refs/pull/*:refs/remotes/origin/pr/*']]])
                }
                dir('sonic-mgmt-common') {
                    checkout([$class: 'GitSCM',
                          branches: [[name: 'refs/heads/master']],
                          userRemoteConfigs: [[url: 'http://github.com/Azure/sonic-mgmt-common']]])
                }
                copyArtifacts(projectName: 'vs/buildimage-vs-all', filter: '**/*.deb', target: 'buildimage', flatten: false)
            }
        }

        stage('Build') {
            steps {
                sh 'NO_TEST_BINS=1 ./scripts/common/sonic-mgmt-common-build/build.sh'
                sh './scripts/common/sonic-mgmt-framework-build/build.sh'
            }
        }

        stage('Test') {
            steps {
                sh './scripts/common/sonic-mgmt-framework-build/test.sh'
            }
        }
    }
    post {
        success {
            archiveArtifacts(artifacts: 'target/*.deb')
        }
    }
}
