pipeline {
    agent { node { label 'sonic-slave' } }

    stages {
        stage('Prepare') {
            steps {
                dir('sairedis') {
                    checkout([$class: 'GitSCM',
                              branches: [[name: '${sha1}']],
                              extensions: [[$class: 'SubmoduleOption',
                                            disableSubmodules: false,
                                            parentCredentials: false,
                                            recursiveSubmodules: true,
                                            reference: '',
                                            trackingSubmodules: false]],
                              userRemoteConfigs: [[url: 'http://github.com/Azure/sonic-sairedis',
                                                   refspec: '+refs/pull/*:refs/remotes/origin/pr/*']]])
                }
                copyArtifacts(projectName: 'common/sonic-swss-common-build', filter: '**/*.deb', target: 'common', flatten: true)
                copyArtifacts(projectName: 'buildimage-vs-all', filter: '**/*.deb', target: 'buildimage', flatten: false)
            }
        }

        stage('Build') {
            steps {
                sh './scripts/vs/sonic-sairedis-build/build.sh'
            }
        }
    }
    post {
        always {
            archiveArtifacts(artifacts: 'target/*.deb, **/*.log, target/syslog')
        }
    }
}
