pipeline {
    agent { node { label 'sonic-slave' } }

    options {
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10'))

    }

    triggers {
        pollSCM('H/10 * * * *')
    }

    stages {
        stage('Prepare') {
            steps {
                dir('sonic-swss-common') {
                    checkout([$class: 'GitSCM',
                              branches: [[name: 'refs/heads/master']],
                              userRemoteConfigs: [[url: 'http://github.com/Azure/sonic-swss-common']]])
                }
                copyArtifacts(projectName: '../vs/buildimage-vs-all', filter: '**/*.deb', target: 'buildimage', flatten: false)
            }
        }

        stage('Build') {
            steps {
                sh './scripts/common/sonic-swss-common-build/build.sh'
            }
        }

        stage('Test') {
            steps {
                sh './scripts/common/sonic-swss-common-build/test.sh'
            }
        }
    }
    post {

        success {
            archiveArtifacts(artifacts: 'target/*.deb')
        }
        fixed {
            slackSend(color:'#00FF00', message: "Build job back to normal: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        regression {
            slackSend(color:'#FF0000', message: "Build job Regression: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
