pipeline {

    options {
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10'))

    }

    triggers {
        pollSCM('@midnight')
    }

    agent { node { label 'jenkins-workers-slow' } }

    stages {
        stage('Prepare') {
            steps {
                checkout([$class: 'GitSCM', 
                          branches: [[name: 'refs/heads/master']],
                          extensions: [[$class: 'SubmoduleOption',
                                        disableSubmodules: false,
                                        parentCredentials: false,
                                        recursiveSubmodules: true,
                                        reference: '',
                                        trackingSubmodules: false]],
                          userRemoteConfigs: [[url: 'http://github.com/Azure/sonic-buildimage']]])
            }
        }

        stage('Build') {
            steps {
                sh '''
#!/bin/bash -x

git submodule foreach --recursive '[ -f .git ] && echo "gitdir: $(realpath --relative-to=. $(cut -d" " -f2 .git))" > .git'

make configure PLATFORM=generic

make SONIC_CONFIG_BUILD_JOBS=1 target/files/stretch/ixgbe.ko \
                               target/debs/stretch/libnl-3-200_3.2.27-2_amd64.deb \
                               target/debs/stretch/libhiredis0.13_0.13.3-2_amd64.deb \
                               target/debs/stretch/redis-server_3.2.4-1~bpo8+1_amd64.deb \
                               target/debs/stretch/libthrift-0.11.0_0.11.0-4_amd64.deb \
                               target/debs/stretch/python3.6_3.6.0-1_amd64.deb \
                               target/debs/stretch/swig3.0_3.0.12-2_amd64.deb \
                               target/debs/stretch/socat_1.7.3.1-2+deb9u1_amd64.deb \
                               target/debs/stretch/libmpdec2_2.4.2-2_amd64.deb \
                               target/debs/stretch/libsnmp-base_5.7.3+dfsg-1.5_all.deb \
                               target/debs/stretch/initramfs-tools_0.130_all.deb \
                               target/debs/stretch/lldpd_0.9.6-1_amd64.deb \
                               target/debs/stretch/lm-sensors_3.4.0-4_amd64.deb \
                               target/debs/stretch/libsensors4_3.4.0-4_amd64.deb \
                               target/debs/stretch/fancontrol_3.4.0-4_all.deb \
                               target/debs/stretch/sensord_3.4.0-4_amd64.deb \
                               target/debs/stretch/smartmontools_6.6-1_amd64.deb \
                               target/debs/stretch/radvd_2.17-2~bpo9+1_amd64.deb
'''
            }
        }

    }
    post {

        success {
            archiveArtifacts(artifacts: 'target/**')
            cleanWs(disableDeferredWipeout: false, deleteDirs: true, notFailBuild: true)
        }
        fixed {
            slackSend(color:'#00FF00', message: "Build job back to normal: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        regression {
            slackSend(color:'#FF0000', message: "Build job Regression: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
