parameters:
- name: arch
  values:
  - amd64
  - armhf
  - arm64
- name: distro
  values:
  - buster
  - jessie
  - stretch

jobs:
- job: Build_${{ parameters.distro }}_${{ parameters.arch }}
  pool: sonicbld
  timeoutInMinutes: 360
  steps:
  - template: cleanup.yml
  - checkout: buildimage
    clean: true
  - bash: |
      set -ex
      docker --version
      echo "Build docker container for ${{ parameters.distro }} and ${{ parameters.arch }}"

      USER=`id -un | tr A-Z a-z`
      SLAVE_DIR=sonic-slave-${{ parameters.distro }}
      if [ x${{ parameters.arch }} == x"amd64" ]; then
        SLAVE_BASE_IMAGE=${SLAVE_DIR}
      else
        SLAVE_BASE_IMAGE=${SLAVE_DIR}-${{ parameters.arch }}
      fi

      tmpfile=$(mktemp)

      echo ${{ parameters.arch }} > .arch

      DOCKER_DATA_ROOT_FOR_MULTIARCH=/data/march/docker BLDENV=${{ parameters.distro }} make -f Makefile.work sonic-slave-build | tee $tmpfile
      SLAVE_BASE_TAG=$(grep "^Checking sonic-slave-base image:" $tmpfile | awk -F ':' '{print $3}')
      SLAVE_TAG=$(grep "^Checking sonic-slave image:" $tmpfile | awk -F ':' '{print $3}')

      echo USER: $USER
      echo SLAVE_BASE_TAG: $SLAVE_BASE_TAG
      echo SLAVE_TAG: $SLAVE_TAG
      mkdir -p target

      docker tag $SLAVE_BASE_IMAGE-$USER:$SLAVE_TAG local/$SLAVE_BASE_IMAGE-$USER:latest
      docker tag $SLAVE_BASE_IMAGE-$USER:$SLAVE_TAG $REGISTRY_SERVER/$SLAVE_BASE_IMAGE-$USER:latest
      docker tag $SLAVE_BASE_IMAGE:$SLAVE_BASE_TAG $REGISTRY_SERVER/$SLAVE_BASE_IMAGE:latest
      docker tag $SLAVE_BASE_IMAGE:$SLAVE_BASE_TAG $REGISTRY_SERVER/$SLAVE_BASE_IMAGE:$SLAVE_BASE_TAG

      echo "##vso[task.setvariable variable=image;]$SLAVE_BASE_IMAGE"
      echo "##vso[task.setvariable variable=user;]$USER"
      echo "##vso[task.setvariable variable=tag;]$SLAVE_BASE_TAG"
    env:
      REGISTRY_SERVER: soniccr2.azurecr.io
    displayName: build sonic-slave-${{ parameters.distro }}-${{ parameters.arch }}

  - bash: |
      echo "aaa$(IMAGE)-$(USER)bbb"
      echo "aaa$(TAG)bbb"
    displayName: show variable
  - task: Docker@2
    inputs:
      containerRegistry: soniccr2
      repository: $(IMAGE)-$(USER)
      command: push
      tags: |
        latest

  - task: Docker@2
    inputs:
      containerRegistry: soniccr2
      repository: $(IMAGE)
      command: push
      tags: |
        $(TAG)
        latest
