#!/bin/bash 
#
# Copyright (c) 2015 Dell Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
# LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
# FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.
#
# See the Apache Version 2.0 License for specific language governing
# permissions and limitations under the License.
#

_dir=$(dirname $0)

rm -f /etc/apt/sources.list.d/*
rm -f /etc/apt/sources.list

cp $_dir/../config/sonic-nas.sources.list /etc/apt/sources.list.d

apt-get update

_dest=$1
shift

apt-get install -d -y --force-yes $*

cp /var/cache/apt/archives/*.deb $_dest

