pipeline {
    agent { node { label 'sonic-slave' } }

    environment {
        SONIC_TEAM_WEBHOOK = credentials('public-jenkins-builder')
    }

    stages {
        stage('Prepare') {
            steps {
                dir('sairedis') {
                    checkout([$class: 'GitSCM',
                              branches: [[name: '*/master']],
                              extensions: [[$class: 'SubmoduleOption',
                                            disableSubmodules: false,
                                            parentCredentials: false,
                                            recursiveSubmodules: true,
                                            reference: '',
                                            trackingSubmodules: false]],
                              userRemoteConfigs: [[url: 'http://github.com/Azure/sonic-sairedis']]])

                }
                copyArtifacts(projectName: 'common/sonic-swss-common-build', filter: '**/*.deb', target: 'common', flatten: true)
                copyArtifacts(projectName: 'buildimage-vs-all', filter: '**/*.deb', target: 'buildimage', flatten: false)
            }
        }

        stage('Build') {
            steps {
                wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                    sh './scripts/vs/sonic-sairedis-build/build.sh'
                }
            }
        }
    }
    post {
        success {
            archiveArtifacts(artifacts: 'target/*.deb, **/*.log, target/var/log/*')
        }
        fixed {
            slackSend(color:'#00FF00', message: "Build job back to normal: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
            office365ConnectorSend(webhookUrl: "${env.SONIC_TEAM_WEBHOOK}")
        }
        regression {
            slackSend(color:'#FF0000', message: "Build job Regression: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
            office365ConnectorSend(webhookUrl: "${env.SONIC_TEAM_WEBHOOK}")
        }
    }
}
