pipeline {
    agent { node { label 'jenkins-vstest-workers' } }

    environment {
        SONIC_TEAM_WEBHOOK = credentials('public-jenkins-builder')
    }

    triggers {
        cron('H H/4 * * *')
    }

    stages {
        stage('Prepare') {
            steps {
                dir('sonic-utilities') {
                    deleteDir()
                    checkout([$class: 'GitSCM',
                          branches: [[name: '*/master']],
                          userRemoteConfigs: [[url: 'https://github.com/Azure/sonic-utilities']]])
                }
                copyArtifacts(projectName: 'common/sonic-swss-common-build', filter: '**/*.deb', target: 'swss-common', flatten: true)
                copyArtifacts(projectName: 'vs/sonic-swss-build', filter: '**/*.deb', target: 'swss', flatten: true)
                copyArtifacts(projectName: 'vs/sonic-sairedis-build', filter: '**/*.deb', target: 'sairedis', flatten: true)
                copyArtifacts(projectName: 'vs/buildimage-vs-all', filter: '**/*', target: 'buildimage', flatten: false)
            }
        }

        stage('Build') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'sonicdev-cr', usernameVariable: 'REGISTRY_USERNAME', passwordVariable: 'REGISTRY_PASSWD')]) {
                    sh './scripts/common/sonic-utilities-build/build.sh'
                }
            }
        }

        stage('Cleanup') {
            steps {
                wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                    sh './scripts/lib/cleanup_vsdocker.sh'
                }
            }
        }

        stage('Test') {
            steps {
                wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                    sh './scripts/common/sonic-utilities-build/test.sh'
                }
            }
        }
    }
    post {
        always {
            junit(allowEmptyResults: true, keepLongStdio: true, testResults: 'sonic-swss-tests/tests/tr.xml')

            publishHTML(target: [
                allowMissing: false,
                alwaysLinkToLastBuild: false,
                keepAll: true,
                reportDir: 'sonic-utilities/htmlcov',
                reportFiles: 'index.html',
                reportName: 'RCov Report'
            ])

            publishCoverage(adapters: [
                coberturaAdapter('sonic-utilities/coverage.xml')
            ])
        }

        success {
            archiveArtifacts(artifacts: 'sonic-utilities/dist/sonic_utilities-1.2-py3-none-any.whl,wheels/sonic_config_engine-1.0-py3-none-any.whl,wheels/swsssdk-2.0.1-py3-none-any.whl,wheels/sonic_py_common-1.0-py3-none-any.whl,wheels/sonic_platform_common-1.0-py3-none-any.whl,sonic-swss-tests/tests/log/**')
        }

        fixed {
            slackSend(color:'#00FF00', message: "Build job back to normal: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
            office365ConnectorSend(webhookUrl: "${env.SONIC_TEAM_WEBHOOK}")
        }

        regression {
            slackSend(color:'#FF0000', message: "Build job Regression: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
            office365ConnectorSend(webhookUrl: "${env.SONIC_TEAM_WEBHOOK}")
        }

        cleanup {
            cleanWs(disableDeferredWipeout: false, deleteDirs: true, notFailBuild: true)
        }
    }
}
